spring.application.name=BackendTFG
# 1. Configuración de la conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/perfumeria_db
spring.datasource.username=root
spring.datasource.password=1234

# 2. Configuración de JPA / Hibernate
# Esto hace que Spring cree las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
# Esto muestra en la consola las frases SQL que Spring hace por ti (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect